### ISSUE TITLE
Viacoin server starting error

### ISSUE THREAD

**Issue by kr1z1s** [viacoin/viacoin#11]
Viacoin server starting

Wallet without GUI
Error during first run viacoind

Restart and resync doesn't help

```
Error: Error initializing wallet database environment "/home/kr1z/.viacoin"!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```

**Comment by romanornr** [comment]
First of all, backup your wallet.dat & dump your private key.

Did you try to restart your pc and resync from scratch? Please don't use a bootstrap.

**Comment by kr1z1s** [comment]
Wallet without GUI
Error during first run viacoind

Restart and resync doesn't help

**Comment by romanornr** [comment]
Did you compile from scratch or use the binaries ?

**Comment by romanornr** [comment]
No reply back. Closing this. 
(use the binary that you can download).
