### ISSUE TITLE
Used the app from the appstore - Coins never got there

### ISSUE THREAD

**Issue by twiiiiiist** [viacoin/viacoin#12]
Hi, I used this app from the appstore. It created a wallet for me. I sent coins to my wallet. The coins never got there and the app keeps creating a new wallet address... I have my backup file emailed to me.. but I have to clue how to decrypt or what to do with this. Are my coins even in there?

**Comment by camelkk** [comment]
There's no official Viacoin app on the appstore. You would have to contact the publisher of the app, as the Viacoin team is no way associated with the wallet on the appstore.

**Comment by romanornr** [comment]
Like camelkk just said.
That app is not created by anyone of the Viacoin team. Contact the publisher of that app.
