### ISSUE TITLE
Shouldn't this be a Fork of Bitcoin?

### ISSUE THREAD

**Issue by vikramdurai** [viacoin/viacoin#16]

**Comment by romanornr** [comment]
Based on Bitcoin Core

**Comment by vikramdurai** [comment]
Yes, this is based on Bitcoin Core, but I meant that the project itself on github should technically be a fork of Bitcoin core

**Comment by romanornr** [comment]
This will definitely keep me awake at night.

**Comment by vikramdurai** [comment]
Hmm..
