### ISSUE TITLE
No peers found

### ISSUE THREAD

**Issue by ralphvn86** [viacoin/viacoin#2]
I do not know it is a real issue, but I installed the Viacoin Core and it is not able to find any peers. So I am not able to download the blockchain? It says "No block source available".

Viacoin Core version v0.10.11.0-145e71b (64-bit)

**Comment by romanornr** [comment]
You are using the old wallet actually. 
You can download 0.13.2.1 beta 

But if you don't want that 
I wrote a tutorial 

https://www.reddit.com/r/viacoin/comments/6hzri2/no_block_source_available_or_failed_to_sync/
