### ISSUE TITLE
Viaelctrum 3.1.3.1 can not synchronize

### ISSUE THREAD

**Issue by Maxim3474** [viacoin/viacoin#21]
Hi dear Developers, i have a Problem, my Viaelectrum can not synchronize, i downloaded Viaelectrum 
 3.1.3.1  yesterday (28.06.2018.), since yesterday it can not synchronize. 
Can you write me a list of current servers?
Thanks

**Comment by Maxim3474** [comment]
Help me please, dont know what to do

**Comment by rohithzr** [comment]
@Maxim3474 
how many peers do you see?
Are you supporting ipv6?

provide more details and logs

**Comment by Maxim3474** [comment]
I'm not very good at this things =) i am on Cyprus on holliday now and where i live, there is only
IPv4  195.175.110.210

**Comment by romanornr** [comment]
Should be solved now.

**Comment by Maxim3474** [comment]
Thanks a lot! It works now!
